import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

import Navbar from '../components/Navbar';
import Sidebar from '../components/Sidebar';
import ReduxProvider from '../components/ReduxProvider'; // Importar el nuevo componente

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Gestor de inventario',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Envolviendo la aplicación en el ReduxProvider */}
        <ReduxProvider>
          <div className="flex h-screen bg-gradient-to-r from-indigo-50 to-indigo-100">
            <Sidebar />
            <div className="flex flex-col flex-1">
              <Navbar />
              {children}
            </div>
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
